sudo: false

language: go

go:
  - 1.6

before_install:
  - export FILE=go_appengine_sdk_linux_amd64-1.9.40.zip
  - curl -O https://storage.googleapis.com/appengine-sdks/featured/$FILE
  - unzip -q $FILE
  - export PATH=$PATH:./go_appengine/
  - goapp get golang.org/x/tools/cmd/cover
  - goapp get github.com/mattn/goveralls
  - goapp get github.com/alecthomas/gometalinter
  - gometalinter --install --update

install:
  - goapp get google.golang.org/appengine
  - goapp get github.com/line/line-bot-sdk-go/linebot
  - goapp get github.com/thingful/httpmock
  - goapp get golang.org/x/text/encoding/japanese
  - goapp get golang.org/x/text/transform

script:
  - make test

after_success:
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
  - gometalinter
